### ISSUE TITLE
Linux EOL causing script failure

### ISSUE THREAD

**Issue by mikerjuk** [illsk1lls/ZipRipper#15]
When running the script on Win10 I see it fail with "The system cannot find the batch label specified - GETJTRREADY".  The label exists, but the Linux EOL in the script are triggering a long standing bug in cmd.  Converting the line endings to CRLF fixes this.

![LinuxEolBug](https://github.com/illsk1lls/ZipRipper/assets/6301752/3e585b52-cc01-48c5-9803-a45fde1cd455)

**Comment by illsk1lls** [comment]
I also want to point out, I have been calling this a “whitespace” issue, because I didn’t know what it was.. and it is the reason there is no indentation in the script and an extra label called :padding. Adding that was allowing it to run until I made these most recent changes. I’m sure if I shuffled it around I could’ve gotten it to run again with the incorrect line endings, but since you pointed out the problem, I will be able to properly indent the script again..

🙏

**Comment by mikerjuk** [comment]
With Linux line ends calls work fine until the label falls on a 512 byte boundary from the call, so just moving things slightly can make or break it.  A big thank you for for a really nice script and great support!
