### ISSUE TITLE
OpenCL unavailable on Nvidia RTXA6000

### ISSUE THREAD

**Issue by aihkla** [illsk1lls/ZipRipper#30]
I tried to crack a .rar and I have no idea how to enable open cl for GPU, it is being forced to run on CPU

**Comment by sascha-broich** [comment]
It's because the cmd-script looks only for `GeForce` and `Quadro`, but not for `RTX`.

You can edit the script with a text editor and clone the lines 899 to 910, replace `GeForce` with `RTX` and save it. Then the script will detect your RTX and the OpenCL.dll.
Tested it myself, having a A2000, and it works.

**Comment by illsk1lls** [comment]
Added RTX A series, A800 (they are beasts), and T1000 professional grade GPU support ;)
